// <auto-generated />
namespace WillPower.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class firstdatalayermigration : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(firstdatalayermigration));
        
        string IMigrationMetadata.Id
        {
            get { return "201910181456388_firstdatalayermigration"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
